/* Generated By:JavaCC: Do not edit this line. CompilerParserConstants.java */
package machine;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CompilerParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int HALT = 4;
  /** RegularExpression Id. */
  int NOP = 5;
  /** RegularExpression Id. */
  int INC = 6;
  /** RegularExpression Id. */
  int DEC = 7;
  /** RegularExpression Id. */
  int JNZ = 8;
  /** RegularExpression Id. */
  int DO = 9;
  /** RegularExpression Id. */
  int WHILE = 10;
  /** RegularExpression Id. */
  int IF = 11;
  /** RegularExpression Id. */
  int ELSE = 12;
  /** RegularExpression Id. */
  int IDENTIFIER = 13;
  /** RegularExpression Id. */
  int NUMBER = 14;
  /** RegularExpression Id. */
  int NEQ = 15;
  /** RegularExpression Id. */
  int EQ = 16;
  /** RegularExpression Id. */
  int COLON = 17;
  /** RegularExpression Id. */
  int COMMENT = 18;
  /** RegularExpression Id. */
  int EOL = 19;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"HALT\"",
    "\"NOP\"",
    "\"INC\"",
    "\"DEC\"",
    "\"JNZ\"",
    "\"do\"",
    "\"while\"",
    "\"if\"",
    "\"else\"",
    "<IDENTIFIER>",
    "<NUMBER>",
    "\"!=\"",
    "\"==\"",
    "\":\"",
    "<COMMENT>",
    "\"\\n\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
  };

}
