/* Generated By:JavaCC: Do not edit this line. CompilerParserConstants.java */
package machine;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CompilerParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int HALT = 5;
  /** RegularExpression Id. */
  int NOP = 6;
  /** RegularExpression Id. */
  int INC = 7;
  /** RegularExpression Id. */
  int DEC = 8;
  /** RegularExpression Id. */
  int JNZ = 9;
  /** RegularExpression Id. */
  int VAR = 10;
  /** RegularExpression Id. */
  int ASSIGN = 11;
  /** RegularExpression Id. */
  int DO = 12;
  /** RegularExpression Id. */
  int WHILE = 13;
  /** RegularExpression Id. */
  int IF = 14;
  /** RegularExpression Id. */
  int ELSE = 15;
  /** RegularExpression Id. */
  int VOID = 16;
  /** RegularExpression Id. */
  int IDENTIFIER = 17;
  /** RegularExpression Id. */
  int NUMBER = 18;
  /** RegularExpression Id. */
  int NEQ = 19;
  /** RegularExpression Id. */
  int EQ = 20;
  /** RegularExpression Id. */
  int COLON = 21;
  /** RegularExpression Id. */
  int EOS = 22;
  /** RegularExpression Id. */
  int BEGIN = 23;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"HALT\"",
    "\"NOP\"",
    "\"INC\"",
    "\"DEC\"",
    "\"JNZ\"",
    "\"var\"",
    "\"=\"",
    "\"do\"",
    "\"while\"",
    "\"if\"",
    "\"else\"",
    "\"void\"",
    "<IDENTIFIER>",
    "<NUMBER>",
    "\"!=\"",
    "\"==\"",
    "\":\"",
    "\";\"",
    "\"begin:\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\"(\"",
    "\")\"",
    "\",\"",
  };

}
